const words = {
  "imageSizeLabel": "בחר גודל תמונה",
  "pageCountSelectLabel": "בחר מספר עמודים",
  "standardSize": "סטנדרטי (4X6)",
  "smallSize": "קטן (3.5X5)",
  "submit": "שלח",
  "required": "שדה חובה",
  "pageSizeExplanation": "יש לכתוב מספר בין 4 ל 11, עבור שברים יש לכתוב ראשית את המספר השלום ואז רווח, ואז את השבר כולל '/', כמו בדוגמה",
  "height": "גובה",
  "width": "רוחב",
  "pageOrientationLabel": "בחר כיוון עמוד, עומד או שוכב",
  "vertical": "עומד",
  "horizontal": "שוכב",
  "FlapName": "פלאפ",
  "DoubleFlapName": "פלאפ כפול",
  "HorizontalFlapName": "פלאפ רוחב",
  "DoubleHorizontalFlapName": "פלאפ רוחב כפול",
  "FallingFlapName": "פלאפ נופל",
  "AccordionName": "אקורדיון",
  "BookName": "ספר",
  "DoubleBookName": "ספר כפול",
  "CloserName": "סוגר",
  "CrossName": "צלב",
  "DoorName": "דלת",
  "FullDoorName": "דלת מלאה",
  "EnvelopeName": "מעטפה",
  "SideEnvelopeName": "מעטפה אנכית",
  "WaterfallName": "מפל",
  "SideWaterfallName": "מפל אורך",
  "MixedName": "מעורב",
  "PulloutName": "נשלף",
  "ReverseName": "רוורס",
  "StrapName": "רצועה"
}

export default words;
